<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1D7_p81' shared service.

return $this->privates['.service_locator.1D7_p81'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService.php', true],
], [
    'authorRepository' => 'App\\Repository\\AuthorRepository',
]);
