<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PbXwDqA' shared service.

return $this->privates['.service_locator.PbXwDqA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'book' => ['privates', '.errored..service_locator.PbXwDqA.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.PbXwDqA": it references class "App\\Entity\\Book" but no such service exists.'],
], [
    'book' => 'App\\Entity\\Book',
]);
