<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XaMpNt8' shared service.

return $this->privates['.service_locator.XaMpNt8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthorController::index' => ['privates', '.service_locator.zdjKxip', 'get_ServiceLocator_ZdjKxipService.php', true],
    'App\\Controller\\BookController::create' => ['privates', '.service_locator.1D7_p81', 'get_ServiceLocator_1D7P81Service.php', true],
    'App\\Controller\\BookController::index' => ['privates', '.service_locator.gIcf5jF', 'get_ServiceLocator_GIcf5jFService.php', true],
    'App\\Controller\\BookController::remove' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController::show' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController::update' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserBookController::destroy' => ['privates', '.service_locator.Ekvw.tk', 'get_ServiceLocator_Ekvw_TkService.php', true],
    'App\\Controller\\UserBookController::index' => ['privates', '.service_locator.f0WG1GB', 'get_ServiceLocator_F0WG1GBService.php', true],
    'App\\Controller\\UserBookController::reserve' => ['privates', '.service_locator.Ekvw.tk', 'get_ServiceLocator_Ekvw_TkService.php', true],
    'App\\Controller\\AuthorController:index' => ['privates', '.service_locator.zdjKxip', 'get_ServiceLocator_ZdjKxipService.php', true],
    'App\\Controller\\BookController:create' => ['privates', '.service_locator.1D7_p81', 'get_ServiceLocator_1D7P81Service.php', true],
    'App\\Controller\\BookController:index' => ['privates', '.service_locator.gIcf5jF', 'get_ServiceLocator_GIcf5jFService.php', true],
    'App\\Controller\\BookController:remove' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController:show' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController:update' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserBookController:destroy' => ['privates', '.service_locator.Ekvw.tk', 'get_ServiceLocator_Ekvw_TkService.php', true],
    'App\\Controller\\UserBookController:index' => ['privates', '.service_locator.f0WG1GB', 'get_ServiceLocator_F0WG1GBService.php', true],
    'App\\Controller\\UserBookController:reserve' => ['privates', '.service_locator.Ekvw.tk', 'get_ServiceLocator_Ekvw_TkService.php', true],
], [
    'App\\Controller\\AuthorController::index' => '?',
    'App\\Controller\\BookController::create' => '?',
    'App\\Controller\\BookController::index' => '?',
    'App\\Controller\\BookController::remove' => '?',
    'App\\Controller\\BookController::show' => '?',
    'App\\Controller\\BookController::update' => '?',
    'App\\Controller\\RegisterController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\UserBookController::destroy' => '?',
    'App\\Controller\\UserBookController::index' => '?',
    'App\\Controller\\UserBookController::reserve' => '?',
    'App\\Controller\\AuthorController:index' => '?',
    'App\\Controller\\BookController:create' => '?',
    'App\\Controller\\BookController:index' => '?',
    'App\\Controller\\BookController:remove' => '?',
    'App\\Controller\\BookController:show' => '?',
    'App\\Controller\\BookController:update' => '?',
    'App\\Controller\\RegisterController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\UserBookController:destroy' => '?',
    'App\\Controller\\UserBookController:index' => '?',
    'App\\Controller\\UserBookController:reserve' => '?',
]);
