<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.f0WG1GB' shared service.

return $this->privates['.service_locator.f0WG1GB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService.php', true],
    'user' => ['privates', '.errored..service_locator.f0WG1GB.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.f0WG1GB": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
    'userBookRepository' => ['privates', 'App\\Repository\\UserBookRepository', 'getUserBookRepositoryService.php', true],
], [
    'bookRepository' => 'App\\Repository\\BookRepository',
    'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
    'userBookRepository' => 'App\\Repository\\UserBookRepository',
]);
