<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ekvw.tk' shared service.

return $this->privates['.service_locator.Ekvw.tk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'book' => ['privates', '.errored..service_locator.Ekvw.tk.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.Ekvw.tk": it references class "App\\Entity\\Book" but no such service exists.'],
    'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService.php', true],
    'user' => ['privates', '.errored..service_locator.Ekvw.tk.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.Ekvw.tk": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
    'userBookRepository' => ['privates', 'App\\Repository\\UserBookRepository', 'getUserBookRepositoryService.php', true],
], [
    'book' => 'App\\Entity\\Book',
    'bookRepository' => 'App\\Repository\\BookRepository',
    'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
    'userBookRepository' => 'App\\Repository\\UserBookRepository',
]);
