<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book extends \App\Entity\Book implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'isbn', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'editorial', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'publishYear', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'userBooks', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'author'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'isbn', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'editorial', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'publishYear', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'userBooks', '' . "\0" . 'App\\Entity\\Book' . "\0" . 'author'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Book $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Book
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsbn(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsbn', []);

        return parent::getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsbn(string $isbn): \App\Entity\Book
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsbn', [$isbn]);

        return parent::setIsbn($isbn);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditorial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditorial', []);

        return parent::getEditorial();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditorial(string $editorial): \App\Entity\Book
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditorial', [$editorial]);

        return parent::setEditorial($editorial);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishYear(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishYear', []);

        return parent::getPublishYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishYear(string $publishYear): \App\Entity\Book
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishYear', [$publishYear]);

        return parent::setPublishYear($publishYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserBooks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserBooks', []);

        return parent::getUserBooks();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserBook(\App\Entity\UserBook $userBook): \App\Entity\Book
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserBook', [$userBook]);

        return parent::addUserBook($userBook);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserBook(\App\Entity\UserBook $userBook): \App\Entity\Book
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserBook', [$userBook]);

        return parent::removeUserBook($userBook);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor(): ?\App\Entity\Author
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor(?\App\Entity\Author $author): \App\Entity\Book
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        return parent::setAuthor($author);
    }

}
