<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBVfYxa3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBVfYxa3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBVfYxa3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBVfYxa3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBVfYxa3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BVfYxa3',
    'container.build_id' => '91681ddf',
    'container.build_time' => 1576115483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBVfYxa3');
