<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5IywTA0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5IywTA0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5IywTA0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5IywTA0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5IywTA0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5IywTA0',
    'container.build_id' => '250f73c6',
    'container.build_time' => 1578568610,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5IywTA0');
